{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 86,
   "id": "30e38480-066e-4af3-b24a-82b2162d8691",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Import Libraries\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import re\n",
    "from sklearn.manifold import TSNE\n",
    "from bokeh.plotting import figure, show, output_notebook\n",
    "from bokeh.models import ColumnDataSource, HoverTool,ColorBar, LinearColorMapper\n",
    "from bokeh.transform import linear_cmap\n",
    "from bokeh.palettes import RdYlGn\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 88,
   "id": "d6ac7f59-bf43-4f49-a97d-45d059e8490c",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Label</th>\n",
       "      <th>Brand</th>\n",
       "      <th>Name</th>\n",
       "      <th>Price</th>\n",
       "      <th>Rank</th>\n",
       "      <th>Ingredients</th>\n",
       "      <th>Combination</th>\n",
       "      <th>Dry</th>\n",
       "      <th>Normal</th>\n",
       "      <th>Oily</th>\n",
       "      <th>Sensitive</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>1407</th>\n",
       "      <td>Sun protect</td>\n",
       "      <td>COOLA</td>\n",
       "      <td>Classic Face SPF 30 - Cucumber</td>\n",
       "      <td>32</td>\n",
       "      <td>4.4</td>\n",
       "      <td>Caprylohydroxamic Acid, Caprylyl Glycol, Carth...</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>119</th>\n",
       "      <td>Moisturizer</td>\n",
       "      <td>BIOSSANCE</td>\n",
       "      <td>Squalane + Omega Repair Cream</td>\n",
       "      <td>58</td>\n",
       "      <td>4.7</td>\n",
       "      <td>Water, Squalane, Glycerin, Caprylic/Capric Tri...</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1373</th>\n",
       "      <td>Sun protect</td>\n",
       "      <td>AMOREPACIFIC</td>\n",
       "      <td>Natural Protector Broad Spectrum SPF 35 Sunscreen</td>\n",
       "      <td>65</td>\n",
       "      <td>4.0</td>\n",
       "      <td>Visit the AMOREPACIFIC boutique</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>54</th>\n",
       "      <td>Moisturizer</td>\n",
       "      <td>TARTE</td>\n",
       "      <td>BB Tinted Treatment 12-Hour Primer Broad Spect...</td>\n",
       "      <td>37</td>\n",
       "      <td>4.3</td>\n",
       "      <td>Cyclopentasiloxane, Isododecane, Mica, Polysil...</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>208</th>\n",
       "      <td>Moisturizer</td>\n",
       "      <td>SK-II</td>\n",
       "      <td>Cellumination Cream EX</td>\n",
       "      <td>160</td>\n",
       "      <td>4.3</td>\n",
       "      <td>Water, Galactomyces Ferment Filtrate (Pitera),...</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "            Label         Brand  \\\n",
       "1407  Sun protect         COOLA   \n",
       "119   Moisturizer     BIOSSANCE   \n",
       "1373  Sun protect  AMOREPACIFIC   \n",
       "54    Moisturizer         TARTE   \n",
       "208   Moisturizer         SK-II   \n",
       "\n",
       "                                                   Name  Price  Rank  \\\n",
       "1407                     Classic Face SPF 30 - Cucumber     32   4.4   \n",
       "119                       Squalane + Omega Repair Cream     58   4.7   \n",
       "1373  Natural Protector Broad Spectrum SPF 35 Sunscreen     65   4.0   \n",
       "54    BB Tinted Treatment 12-Hour Primer Broad Spect...     37   4.3   \n",
       "208                              Cellumination Cream EX    160   4.3   \n",
       "\n",
       "                                            Ingredients  Combination  Dry  \\\n",
       "1407  Caprylohydroxamic Acid, Caprylyl Glycol, Carth...            1    1   \n",
       "119   Water, Squalane, Glycerin, Caprylic/Capric Tri...            1    1   \n",
       "1373                    Visit the AMOREPACIFIC boutique            1    1   \n",
       "54    Cyclopentasiloxane, Isododecane, Mica, Polysil...            1    1   \n",
       "208   Water, Galactomyces Ferment Filtrate (Pitera),...            1    1   \n",
       "\n",
       "      Normal  Oily  Sensitive  \n",
       "1407       1     0          1  \n",
       "119        1     0          1  \n",
       "1373       1     1          1  \n",
       "54         1     1          0  \n",
       "208        1     1          1  "
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Product Type Counts:\n",
      "Label\n",
      "Moisturizer    298\n",
      "Cleanser       281\n",
      "Face Mask      266\n",
      "Treatment      248\n",
      "Eye cream      209\n",
      "Sun protect    170\n",
      "Name: count, dtype: int64\n"
     ]
    }
   ],
   "source": [
    "# Load the dataset\n",
    "df = pd.read_csv(r'C:\\Users\\bnith\\Downloads\\dataset\\datasets\\cosmetics.csv')\n",
    "\n",
    "# Display a sample of five random rows from the dataset\n",
    "display(df.sample(5))\n",
    "\n",
    "# Display counts of each product type in the 'Label' column\n",
    "print(\"Product Type Counts:\")\n",
    "print(df['Label'].value_counts())\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 90,
   "id": "b15894e7-5411-4b2b-ab82-bc7921deac80",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "            Label                          Brand  \\\n",
      "0     Moisturizer                         LA MER   \n",
      "1     Moisturizer                          SK-II   \n",
      "2     Moisturizer                 DRUNK ELEPHANT   \n",
      "3     Moisturizer                         LA MER   \n",
      "4     Moisturizer                   IT COSMETICS   \n",
      "...           ...                            ...   \n",
      "1467  Sun Protect                         KORRES   \n",
      "1468  Sun Protect                KATE SOMERVILLE   \n",
      "1469  Sun Protect                  VITA LIBERATA   \n",
      "1470  Sun Protect  ST. TROPEZ TANNING ESSENTIALS   \n",
      "1471  Sun Protect                     DERMAFLASH   \n",
      "\n",
      "                                                   Name  Price  Rank  \\\n",
      "0                                       Crème de la Mer    175   4.1   \n",
      "1                              Facial Treatment Essence    179   4.1   \n",
      "2                            Protini™ Polypeptide Cream     68   4.4   \n",
      "3                           The Moisturizing Soft Cream    175   3.8   \n",
      "4         Your Skin But Better™ CC+™ Cream with SPF 50+     38   4.1   \n",
      "...                                                 ...    ...   ...   \n",
      "1467  Yoghurt Nourishing Fluid Veil Face Sunscreen B...     35   3.9   \n",
      "1468  Daily Deflector™ Waterlight Broad Spectrum SPF...     48   3.6   \n",
      "1469                            Self Tan Dry Oil SPF 50     54   3.5   \n",
      "1470                   Pro Light Self Tan Bronzing Mist     20   1.0   \n",
      "1471  DERMAPROTECT Daily Defense Broad Spectrum SPF 50+     45   0.0   \n",
      "\n",
      "                                            Ingredients  Combination  Dry  \\\n",
      "0     algae (seaweed) extract, mineral oil, petrolat...            1    1   \n",
      "1     galactomyces ferment filtrate (pitera), butyle...            1    1   \n",
      "2     water, dicaprylyl carbonate, glycerin, ceteary...            1    1   \n",
      "3     algae (seaweed) extract, cyclopentasiloxane, p...            1    1   \n",
      "4     water, snail secretion filtrate, phenyl trimet...            1    1   \n",
      "...                                                 ...          ...  ...   \n",
      "1467  water, alcohol denat., potassium cetyl phospha...            1    1   \n",
      "1468  water, isododecane, dimethicone, butyloctyl sa...            0    0   \n",
      "1469  water, dihydroxyacetone, glycerin, sclerocarya...            0    0   \n",
      "1470  water, dihydroxyacetone, propylene glycol, ppg...            0    0   \n",
      "1471                      visit the dermaflash boutique            1    1   \n",
      "\n",
      "      Normal  Oily  Sensitive  \n",
      "0          1     1          1  \n",
      "1          1     1          1  \n",
      "2          1     1          0  \n",
      "3          1     1          1  \n",
      "4          1     1          1  \n",
      "...      ...   ...        ...  \n",
      "1467       1     1          1  \n",
      "1468       0     0          0  \n",
      "1469       0     0          0  \n",
      "1470       0     0          0  \n",
      "1471       1     1          1  \n",
      "\n",
      "[1472 rows x 11 columns]\n"
     ]
    }
   ],
   "source": [
    "#  Remove duplicate rows\n",
    "df.drop_duplicates(inplace=True)\n",
    "\n",
    "#  Drop rows with missing essential data\n",
    "df.dropna(subset=['Ingredients', 'Label', 'Price'], inplace=True)\n",
    "\n",
    "# Clean the 'Ingredients' column:\n",
    "# - Remove leading/trailing spaces\n",
    "# - Convert to lowercase\n",
    "# - Remove HTML tags if present\n",
    "\n",
    "df['Ingredients'] = df['Ingredients'].str.strip().str.lower()\n",
    "df['Ingredients'] = df['Ingredients'].apply(lambda x: re.sub(r'<.*?>', '', x))\n",
    "\n",
    "#  Clean the 'Label' column (Product Category)\n",
    "df['Label'] = df['Label'].str.strip().str.title()\n",
    "\n",
    "#  Convert 'Price' to numeric, handle errors\n",
    "df['Price'] = pd.to_numeric(df['Price'], errors='coerce')\n",
    "\n",
    "#  Drop rows with missing or invalid prices after conversion\n",
    "df.dropna(subset=['Price'], inplace=True)\n",
    "\n",
    "print(df)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 100,
   "id": "8fa6b8a5-c556-4e1c-bc21-2fa96e03152d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Filtered dataset shape: (204, 11)\n"
     ]
    }
   ],
   "source": [
    "#  Filter the data for Moisturizers and Oily Skin\n",
    "\n",
    "# Filter for 'Moisturizer' in the 'Label' column\n",
    "Sun protect = df[df['Label'] == 'Sun protect']\n",
    "\n",
    "# Further filter for products suitable for dry skin (Oily column == 1)\n",
    "moisturizers_Sun protect  = Sun protect[Sun protect['Normal'] == 1]\n",
    "\n",
    "# Reset the index after filtering\n",
    "Sun protect_Normal  = Sun protect_Normal.reset_index(drop=True)\n",
    "\n",
    "# Display the filtered data shape\n",
    "print(\"Filtered dataset shape:\",Sun protect_Normal.shape)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 108,
   "id": "96f8afc1-2dd7-4eba-bdd7-76224681ce17",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The index for decyl oleate is 25\n"
     ]
    }
   ],
   "source": [
    "# Tokenize the ingredients and create a bag of words\n",
    "\n",
    "# Initialize dictionary, list, and initial index\n",
    "ingredient_idx = {}\n",
    "corpus = []\n",
    "idx = 0\n",
    "\n",
    "# For loop for tokenization\n",
    "for i in range(len(moisturizers_Normal)):    \n",
    "    # Get the ingredients of each product\n",
    "    ingredients = moisturizers_Normal['Ingredients'][i]\n",
    "    \n",
    "    # Convert ingredients to lowercase\n",
    "    ingredients_lower = ingredients.lower()\n",
    "    \n",
    "    # Split the ingredients into tokens based on ', '\n",
    "    tokens = ingredients_lower.split(', ')\n",
    "    \n",
    "    # Append the list of tokens to the corpus\n",
    "    corpus.append(tokens)\n",
    "    \n",
    "    # Build the ingredient index dictionary\n",
    "    for ingredient in tokens:\n",
    "        if ingredient not in ingredient_idx:\n",
    "            ingredient_idx[ingredient] = idx\n",
    "            idx += 1\n",
    "            \n",
    "#  Check the index of a specific ingredient\n",
    "print(\"The index for decyl oleate is\", ingredient_idx['decyl oleate'])\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 110,
   "id": "f7660d34-935b-471e-9555-54ca65cee509",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Document-Term Matrix shape (M x N): (204, 2315)\n"
     ]
    }
   ],
   "source": [
    "# Initialize a Document-Term Matrix (DTM)\n",
    "\n",
    "# Get the total number of products (documents)\n",
    "M = len(moisturizers_Normal)\n",
    "\n",
    "# Get the total number of unique ingredients (terms)\n",
    "N = len(ingredient_idx)\n",
    "\n",
    "# Initialize a matrix of zeros with size M x N\n",
    "A = np.zeros((M, N))\n",
    "\n",
    "# Display the shape of the matrix\n",
    "print(\"Document-Term Matrix shape (M x N):\", A.shape)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 112,
   "id": "8a0d23d5-92a4-445c-8bda-2d10a75c4a27",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Define the oh_encoder function\n",
    "def oh_encoder(tokens):\n",
    "    # Initialize a zero vector of length N (total number of unique ingredients)\n",
    "    x = np.zeros(N)\n",
    "    \n",
    "    # For each ingredient in the token list\n",
    "    for ingredient in tokens:\n",
    "        # Get the index of the ingredient from ingredient_idx dictionary\n",
    "        idx = ingredient_idx.get(ingredient)\n",
    "        \n",
    "        # If the ingredient exists in the dictionary, set the corresponding index to 1\n",
    "        if idx is not None:\n",
    "            x[idx] = 1\n",
    "            \n",
    "    # Return the one-hot encoded vector\n",
    "    return x\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 114,
   "id": "8d63b6dc-a03a-4353-b8b3-8d6c5b4e87df",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Get the binary value of the tokens for each row of matrix A\n",
    "\n",
    "# Initialize row index\n",
    "i = 0\n",
    "\n",
    "# Loop through each tokenized ingredient list (each product)\n",
    "for tokens in corpus:\n",
    "    # Apply the oh_encoder function to get the one-hot encoded vector\n",
    "    A[i, :] = oh_encoder(tokens)\n",
    "    \n",
    "    # Increment row index\n",
    "    i += 1\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 118,
   "id": "6c47bde4-7b4d-4081-a47d-fa5eada0e01a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "           Label            Brand  \\\n",
      "0    Moisturizer           LA MER   \n",
      "1    Moisturizer            SK-II   \n",
      "2    Moisturizer   DRUNK ELEPHANT   \n",
      "3    Moisturizer           LA MER   \n",
      "4    Moisturizer     IT COSMETICS   \n",
      "..           ...              ...   \n",
      "199  Moisturizer         SHISEIDO   \n",
      "200  Moisturizer    SATURDAY SKIN   \n",
      "201  Moisturizer           LA MER   \n",
      "202  Moisturizer  KATE SOMERVILLE   \n",
      "203  Moisturizer            GO-TO   \n",
      "\n",
      "                                                  Name  Price  Rank  \\\n",
      "0                                      Crème de la Mer    175   4.1   \n",
      "1                             Facial Treatment Essence    179   4.1   \n",
      "2                           Protini™ Polypeptide Cream     68   4.4   \n",
      "3                          The Moisturizing Soft Cream    175   3.8   \n",
      "4        Your Skin But Better™ CC+™ Cream with SPF 50+     38   4.1   \n",
      "..                                                 ...    ...   ...   \n",
      "199  White Lucent All Day Brightener Broad Spectrum...     62   4.6   \n",
      "200             Featherweight Daily Moisturizing Cream     49   4.6   \n",
      "201                      The Moisturizing Matte Lotion    270   3.9   \n",
      "202                       Goat Milk Moisturizing Cream     65   4.1   \n",
      "203                                          Face Hero     34   4.8   \n",
      "\n",
      "                                           Ingredients  Combination  Dry  \\\n",
      "0    algae (seaweed) extract, mineral oil, petrolat...            1    1   \n",
      "1    galactomyces ferment filtrate (pitera), butyle...            1    1   \n",
      "2    water, dicaprylyl carbonate, glycerin, ceteary...            1    1   \n",
      "3    algae (seaweed) extract, cyclopentasiloxane, p...            1    1   \n",
      "4    water, snail secretion filtrate, phenyl trimet...            1    1   \n",
      "..                                                 ...          ...  ...   \n",
      "199  water, sd alcohol 40-b, dimethicone, dipropyle...            1    1   \n",
      "200  water, butylene glycol, ethylhexyl palmitate, ...            1    1   \n",
      "201  water, algae (seaweed) extract, propanediol, s...            0    0   \n",
      "202  water, ethylhexyl palmitate, myristyl myristat...            1    1   \n",
      "203  almond oil, jojoba oil, macadamia oil, brazil ...            1    1   \n",
      "\n",
      "     Normal  Oily  Sensitive           X           Y  \n",
      "0         1     1          1 -285.176117  136.273499  \n",
      "1         1     1          1   22.485809 -131.892410  \n",
      "2         1     1          0 -290.771057   56.670456  \n",
      "3         1     1          1  115.453491  301.645477  \n",
      "4         1     1          1 -202.643158  212.309860  \n",
      "..      ...   ...        ...         ...         ...  \n",
      "199       1     0          0  -27.081240  -84.084030  \n",
      "200       1     1          1   24.247427  301.477905  \n",
      "201       1     1          0  146.336426  285.102631  \n",
      "202       1     1          1  207.716156  -32.171932  \n",
      "203       1     1          1  -45.601337 -139.671844  \n",
      "\n",
      "[204 rows x 13 columns]\n"
     ]
    }
   ],
   "source": [
    "# Dimension reduction with t-SNE\n",
    "\n",
    "# Create a TSNE instance with specified parameters\n",
    "model = TSNE(n_components=2, learning_rate=200, random_state=42)\n",
    "\n",
    "# Apply t-SNE to the Document-Term Matrix A\n",
    "tsne_features = model.fit_transform(A)\n",
    "\n",
    "# Create new columns 'X' and 'Y' in the moisturizers_dry DataFrame to store t-SNE results\n",
    "moisturizers_Normal ['X'] = tsne_features[:, 0]  # First dimension\n",
    "moisturizers_Normal ['Y'] = tsne_features[:, 1]  # Second dimension\n",
    "\n",
    "# Optional: Display first few results\n",
    "print(moisturizers_Normal)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 122,
   "id": "c3402d98-ce9c-487b-8f8e-0cf2a61aa8e3",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div style=\"display: table;\"><div style=\"display: table-row;\"><div style=\"display: table-cell;\"><b title=\"bokeh.models.renderers.glyph_renderer.GlyphRenderer\">GlyphRenderer</b>(</div><div style=\"display: table-cell;\">id&nbsp;=&nbsp;'p1248', <span id=\"p1252\" style=\"cursor: pointer;\">&hellip;)</span></div></div><div class=\"p1251\" style=\"display: none;\"><div style=\"display: table-cell;\"></div><div style=\"display: table-cell;\">context_menu&nbsp;=&nbsp;None,</div></div><div class=\"p1251\" style=\"display: none;\"><div style=\"display: table-cell;\"></div><div style=\"display: table-cell;\">coordinates&nbsp;=&nbsp;None,</div></div><div class=\"p1251\" style=\"display: none;\"><div style=\"display: table-cell;\"></div><div style=\"display: table-cell;\">css_classes&nbsp;=&nbsp;[],</div></div><div class=\"p1251\" style=\"display: none;\"><div style=\"display: table-cell;\"></div><div style=\"display: table-cell;\">css_variables&nbsp;=&nbsp;{},</div></div><div class=\"p1251\" style=\"display: none;\"><div style=\"display: table-cell;\"></div><div style=\"display: table-cell;\">data_source&nbsp;=&nbsp;ColumnDataSource(id='p1203', ...),</div></div><div class=\"p1251\" style=\"display: none;\"><div style=\"display: table-cell;\"></div><div style=\"display: table-cell;\">glyph&nbsp;=&nbsp;Scatter(id='p1245', ...),</div></div><div class=\"p1251\" style=\"display: none;\"><div style=\"display: table-cell;\"></div><div style=\"display: table-cell;\">group&nbsp;=&nbsp;None,</div></div><div class=\"p1251\" style=\"display: none;\"><div style=\"display: table-cell;\"></div><div style=\"display: table-cell;\">hover_glyph&nbsp;=&nbsp;None,</div></div><div class=\"p1251\" style=\"display: none;\"><div style=\"display: table-cell;\"></div><div style=\"display: table-cell;\">js_event_callbacks&nbsp;=&nbsp;{},</div></div><div class=\"p1251\" style=\"display: none;\"><div style=\"display: table-cell;\"></div><div style=\"display: table-cell;\">js_property_callbacks&nbsp;=&nbsp;{},</div></div><div class=\"p1251\" style=\"display: none;\"><div style=\"display: table-cell;\"></div><div style=\"display: table-cell;\">level&nbsp;=&nbsp;'glyph',</div></div><div class=\"p1251\" style=\"display: none;\"><div style=\"display: table-cell;\"></div><div style=\"display: table-cell;\">muted&nbsp;=&nbsp;False,</div></div><div class=\"p1251\" style=\"display: none;\"><div style=\"display: table-cell;\"></div><div style=\"display: table-cell;\">muted_glyph&nbsp;=&nbsp;Scatter(id='p1247', ...),</div></div><div class=\"p1251\" style=\"display: none;\"><div style=\"display: table-cell;\"></div><div style=\"display: table-cell;\">name&nbsp;=&nbsp;None,</div></div><div class=\"p1251\" style=\"display: none;\"><div style=\"display: table-cell;\"></div><div style=\"display: table-cell;\">nonselection_glyph&nbsp;=&nbsp;Scatter(id='p1246', ...),</div></div><div class=\"p1251\" style=\"display: none;\"><div style=\"display: table-cell;\"></div><div style=\"display: table-cell;\">propagate_hover&nbsp;=&nbsp;False,</div></div><div class=\"p1251\" style=\"display: none;\"><div style=\"display: table-cell;\"></div><div style=\"display: table-cell;\">selection_glyph&nbsp;=&nbsp;'auto',</div></div><div class=\"p1251\" style=\"display: none;\"><div style=\"display: table-cell;\"></div><div style=\"display: table-cell;\">styles&nbsp;=&nbsp;{},</div></div><div class=\"p1251\" style=\"display: none;\"><div style=\"display: table-cell;\"></div><div style=\"display: table-cell;\">stylesheets&nbsp;=&nbsp;[],</div></div><div class=\"p1251\" style=\"display: none;\"><div style=\"display: table-cell;\"></div><div style=\"display: table-cell;\">subscribed_events&nbsp;=&nbsp;PropertyValueSet(),</div></div><div class=\"p1251\" style=\"display: none;\"><div style=\"display: table-cell;\"></div><div style=\"display: table-cell;\">syncable&nbsp;=&nbsp;True,</div></div><div class=\"p1251\" style=\"display: none;\"><div style=\"display: table-cell;\"></div><div style=\"display: table-cell;\">tags&nbsp;=&nbsp;[],</div></div><div class=\"p1251\" style=\"display: none;\"><div style=\"display: table-cell;\"></div><div style=\"display: table-cell;\">view&nbsp;=&nbsp;CDSView(id='p1249', ...),</div></div><div class=\"p1251\" style=\"display: none;\"><div style=\"display: table-cell;\"></div><div style=\"display: table-cell;\">visible&nbsp;=&nbsp;True,</div></div><div class=\"p1251\" style=\"display: none;\"><div style=\"display: table-cell;\"></div><div style=\"display: table-cell;\">x_range_name&nbsp;=&nbsp;'default',</div></div><div class=\"p1251\" style=\"display: none;\"><div style=\"display: table-cell;\"></div><div style=\"display: table-cell;\">y_range_name&nbsp;=&nbsp;'default')</div></div></div>\n",
       "<script>\n",
       "(function() {\n",
       "  let expanded = false;\n",
       "  const ellipsis = document.getElementById(\"p1252\");\n",
       "  ellipsis.addEventListener(\"click\", function() {\n",
       "    const rows = document.getElementsByClassName(\"p1251\");\n",
       "    for (let i = 0; i < rows.length; i++) {\n",
       "      const el = rows[i];\n",
       "      el.style.display = expanded ? \"none\" : \"table-row\";\n",
       "    }\n",
       "    ellipsis.innerHTML = expanded ? \"&hellip;)\" : \"&lsaquo;&lsaquo;&lsaquo;\";\n",
       "    expanded = !expanded;\n",
       "  });\n",
       "})();\n",
       "</script>\n"
      ],
      "text/plain": [
       "GlyphRenderer(id='p1248', ...)"
      ]
     },
     "execution_count": 122,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Create a ColumnDataSource with the moisturizers_dry DataFrame\n",
    "source = ColumnDataSource(moisturizers_Normal)\n",
    "\n",
    "# Create the figure with axis labels\n",
    "plot = figure(x_axis_label='T-SNE 1', \n",
    "              y_axis_label='T-SNE 2', \n",
    "              width=500, height=400,\n",
    "              title=\"t-SNE Scatter Plot of Moisturizers for Normal Skin\")\n",
    "\n",
    "# Create a linear color mapper based on Price (green = low price, red = high price)\n",
    "color_mapper = linear_cmap(field_name='Price', palette=RdYlGn[11][::1], low=moisturizers_Normal['Price'].min(), high=moisturizers_Normal['Price'].max())\n",
    "\n",
    "# Add the scatter plot with color based on price\n",
    "plot.scatter(x='X', \n",
    "             y='Y', \n",
    "             source=source, \n",
    "             size=10, \n",
    "             color=color_mapper, \n",
    "             alpha=0.8)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 124,
   "id": "29857cea-7628-4466-962c-9374fe9cc309",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Create a HoverTool object\n",
    "hover = HoverTool(tooltips=[\n",
    "    ('Item', '@Name'),\n",
    "    ('Brand', '@Brand'),\n",
    "    ('Price', '$@Price'),\n",
    "    ('Rank', '@Rank')\n",
    "])\n",
    "\n",
    "# Add the hover tool to the plot\n",
    "plot.add_tools(hover)\n",
    "\n",
    "# Add color bar to indicate price scale\n",
    "color_bar = ColorBar(color_mapper=color_mapper['transform'], label_standoff=12, location=(0,0))\n",
    "plot.add_layout(color_bar, 'right')\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 126,
   "id": "003396a7-3d45-4956-ac17-3e593fe2e95f",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Display the plot\n",
    "show(plot)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "75f0d591-6b5e-49cf-b791-b5e79af9abab",
   "metadata": {},
   "outputs": [],
   "source": [
    "#  Print the ingredients for two similar products\n",
    "\n",
    "# Filter the first product by name\n",
    "cosmetic_1 = moisturizers_dry[moisturizers_dry['Name'] == \"Color Control Cushion Compact Broad Spectrum SPF 50+\"]\n",
    "\n",
    "# Filter the second product by name\n",
    "cosmetic_2 = moisturizers_dry[moisturizers_dry['Name'] == \"BB Cushion Hydra Radiance SPF 50\"]\n",
    "\n",
    "# Display the data and ingredients of the first product\n",
    "display(cosmetic_1)\n",
    "print(\"Ingredients of Color Control Cushion Compact Broad Spectrum SPF 50+:\\n\", cosmetic_1.Ingredients.values[0])\n",
    "\n",
    "# Display the data and ingredients of the second product\n",
    "display(cosmetic_2)\n",
    "print(\"Ingredients of BB Cushion Hydra Radiance SPF 50:\\n\", cosmetic_2.Ingredients.values[0])\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "da063811-2133-4f67-9119-ba66128f3f8a",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
